id: IC2181CC7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:42:42+00:00'
last_modified: '2022-06-08T01:16:18.307745+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14777
  title: ས་མཐོའི་བུ་མོ། ༼དུས་དེབ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    22A2:
      image_group_id: I2PD18718
      title: ''
      total_pages: 188
      order: 1
      base_file: 22A2.txt
    BB41:
      image_group_id: I2PD18719
      title: ''
      total_pages: 216
      order: 2
      base_file: BB41.txt
    D17E:
      image_group_id: I2PD18720
      title: ''
      total_pages: 190
      order: 3
      base_file: D17E.txt
    4A38:
      image_group_id: I2PD18721
      title: ''
      total_pages: 170
      order: 4
      base_file: 4A38.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
